[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:queue]
command=php /var/www/artisan queue:work --tries=1 --sleep=3 --max-time=3600
autorestart=true

[program:schedule]
command=php /var/www/artisan schedule:work
autorestart=true
